#!/usr/bin/env python3
"""
InvestPal Polymarket Engine — One-command Setup & Launch

Usage:
    python setup.py [command]

Commands:
    install     Install all dependencies (run once)
    configure   Interactive setup wizard for .env
    check       Verify installation and connectivity
    start       Start the trade engine server
    run         Alias for 'start'
    demo        Start in demo simulation mode (no real funds needed)
    testnet     Start in testnet mode (Mumbai — requires test tokens)
"""
import os, sys, subprocess, json, shutil

BASE = os.path.dirname(os.path.abspath(__file__))
ENV_FILE = os.path.join(BASE, ".env")
CFG_FILE = os.path.join(BASE, "data", "config.json")

def cmd_install():
    print("=" * 60)
    print("  InvestPal Polymarket Engine — Installing Dependencies")
    print("=" * 60)
    pip = [sys.executable, "-m", "pip", "install", "--upgrade"]
    req = os.path.join(BASE, "requirements.txt")
    # Install core deps
    for pkg in ["pip", "setuptools", "wheel"]:
        subprocess.check_call(pip + [pkg])
    subprocess.check_call(pip + ["-r", req])
    # Verify py-clob-client-v2
    try:
        import py_clob_client_v2
        print(f"  py-clob-client-v2 {py_clob_client_v2.__version__} installed ✓")
    except ImportError:
        print("  Installing py-clob-client-v2...")
        subprocess.check_call(pip + ["py-clob-client-v2==1.1.0"])
    print("\n✅ All dependencies installed.")
    print("   Next: python setup.py configure")

def cmd_configure():
    print("=" * 60)
    print("  InvestPal Polymarket Engine — Setup Wizard")
    print("=" * 60)
    print("  Leave blank to skip any field.\n")
    env = {}
    if os.path.isfile(ENV_FILE):
        for line in open(ENV_FILE):
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                env[k.strip()] = v.strip()

    def ask(prompt, key, secret=False):
        current = env.get(key, "")
        default = f" [{current[:12]}...]" if current and len(current) > 12 else (f" [{current}]" if current else "")
        val = input(f"  {prompt}{default}: ").strip()
        if val:
            env[key] = val
        return val or current

    print("\n  ── Wallet (Required for live trading) ──")
    ask("Private key (0x...)", "POLYMARKET_PRIVATE_KEY")
    ask("Funder/deposit wallet address", "POLYMARKET_FUNDER_ADDRESS")
    print("\n  ── Polymarket Builder API (Required for POLY_1271) ──")
    ask("Builder API key", "POLYMARKET_BUILDER_KEY")
    ask("Builder API secret", "POLYMARKET_BUILDER_SECRET")
    ask("Builder API passphrase", "POLYMARKET_BUILDER_PASSPHRASE")
    print("\n  ── Network ──")
    print("  137 = Polygon Mainnet (LIVE), 80001 = Mumbai Testnet")
    ask("Chain ID", "CHAIN_ID")
    print("\n  ── Proxy (optional, for restricted regions) ──")
    ask("HTTP/SOCKS proxy URL", "POLYMARKET_PROXY")
    use = input("  Use Tor? (y/N): ").strip().lower()
    if use == "y":
        env["POLYMARKET_USE_TOR"] = "true"

    # Write .env
    with open(ENV_FILE, "w") as f:
        f.write(f"# InvestPal Polymarket Engine — Generated by setup.py\n")
        f.write(f"# Generated: {__import__('datetime').datetime.now().isoformat()}\n\n")
        for k, v in sorted(env.items()):
            if v:
                f.write(f"{k}={v}\n")
    print(f"\n✅ .env written to {ENV_FILE}")
    print("   Next: python setup.py start")

def cmd_check():
    print("=" * 60)
    print("  InvestPal Polymarket Engine — Connectivity Check")
    print("=" * 60)
    sys.path.insert(0, BASE)
    # Load env
    for line in open(ENV_FILE) if os.path.isfile(ENV_FILE) else []:
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, _, v = line.partition("=")
            os.environ[k.strip()] = v.strip().strip("\"").strip("'")

    pk = os.environ.get("POLYMARKET_PRIVATE_KEY", "")
    dw = os.environ.get("POLYMARKET_FUNDER_ADDRESS", "")
    bk = os.environ.get("POLYMARKET_BUILDER_KEY", "")

    print(f"\n  Config:")
    print(f"    Private key:     {'✓' if pk and len(pk) > 10 else '✗'}")
    print(f"    Deposit wallet:  {'✓' if dw else '✗'}")
    print(f"    Builder API key: {'✓' if bk else '✗'}")

    # Test imports
    print("\n  Dependencies:")
    for mod in ["requests", "eth_account", "py_clob_client_v2", "py_builder_signing_sdk"]:
        try:
            __import__(mod.replace("-", "_"))
            print(f"    {mod}: ✓")
        except ImportError:
            print(f"    {mod}: ✗ (run 'python setup.py install')")

    # Test RPC connectivity
    print("\n  Connectivity:")
    import requests
    rpc = "https://polygon.gateway.tenderly.co"
    try:
        r = requests.post(rpc, json={"jsonrpc": "2.0", "method": "eth_blockNumber", "params": [], "id": 1}, timeout=10)
        if r.ok:
            bn = int(r.json().get("result", "0x0"), 16)
            print(f"    RPC (Polygon): ✓ (block {bn})")
        else:
            print(f"    RPC: ✗ ({r.status_code})")
    except Exception as e:
        print(f"    RPC: ✗ ({e})")

    # Test Gamma API
    try:
        r = requests.get("https://gamma-api.polymarket.com/markets", params={"limit": 1, "closed": "false"}, timeout=10)
        if r.ok:
            print(f"    Gamma API: ✓ ({len(r.json())} markets)")
        else:
            print(f"    Gamma API: ✗ ({r.status_code})")
    except Exception as e:
        print(f"    Gamma API: ✗ ({e})")

    # Test CLOB
    try:
        r = requests.get("https://clob.polymarket.com/feature-flags", timeout=10)
        print(f"    CLOB: {'✓' if r.ok else '✗ (' + str(r.status_code) + ')'}")
    except Exception as e:
        print(f"    CLOB: ✗ ({e})")

    # Check balances if private key available
    if pk and len(pk) > 10:
        from eth_account import Account
        Account.enable_unaudited_hdwallet_features()
        acct = Account.from_key(pk)
        eoa = acct.address
        print(f"\n  Wallet: {eoa}")
        def tok_bal(contract, addr):
            sel = "0x70a08231" + addr[2:].lower().zfill(64)
            try:
                r = requests.post(rpc, json={"jsonrpc":"2.0","method":"eth_call","params":[{"to":contract,"data":sel},"latest"],"id":1}, timeout=10)
                if r.ok: return int(r.json().get("result","0x0"), 16) / 1e6
            except: pass
            return 0
        print(f"    USDC (native): ${tok_bal('0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359', eoa):.2f}")
        print(f"    USDC.e: ${tok_bal('0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174', eoa):.2f}")
        if dw:
            dp = tok_bal("0xC011a7E12a19f7B1f670d46F03B03f3342E82DFB", dw)
            print(f"    Deposit wallet pUSD: ${dp:.4f}")
            print(f"    {'⚠ Needs funding (below $1)' if dp < 1.0 else '✓ Balance OK'}")

    print("\n  Done.")

def cmd_start():
    sys.path.insert(0, BASE)
    # Load .env
    try:
        from dotenv import load_dotenv
        load_dotenv(os.path.join(BASE, ".env"))
    except: pass
    # Force env vars from .env
    if os.path.isfile(ENV_FILE):
        for line in open(ENV_FILE):
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                os.environ[k.strip()] = v.strip().strip("\"").strip("'")
    from server import main
    main()

def cmd_demo():
    """Start in demo simulation mode with $10,000 virtual bankroll."""
    os.environ["INVESTPAL_MODE"] = "demo"
    from core.bot import save_config
    cfg = {
        "bot_enabled": True, "bot_mode": "simulation",
        "order_type": "poly1271", "auto_fund": False,
        "base_stake": 10.0, "recovery_factor": 2.0,
        "max_concurrent": 3, "bankroll": 10000.0,
        "balance_filter": 0.30, "interval_seconds": 60,
        "demo_mode": True, "demo_bankroll": 10000.0,
    }
    save_config(cfg)
    print("=" * 60)
    print("  InvestPal DEMO MODE — $10,000 Virtual Bankroll")
    print("  No real funds at risk. Real market data, virtual execution.")
    print("=" * 60)
    cmd_start()

def cmd_testnet():
    os.environ["INVESTPAL_MODE"] = "testnet"
    os.environ["CHAIN_ID"] = "80001"
    print("=" * 60)
    print("  InvestPal TESTNET MODE — Polygon Mumbai")
    print("  Uses testnet contracts. Requires test MATIC + USDC.")
    print("=" * 60)
    cmd_start()

def cmd_guide():
    print("=" * 60)
    print("  InvestPal Polymarket Engine — User Guide")
    print("=" * 60)
    print("""
  QUICK START:
    1. python setup.py install     # Install deps (one-time)
    2. python setup.py configure    # Set up your wallet
    3. python setup.py check        # Verify everything works
    4. python setup.py demo         # Test with $10K virtual money
    5. python setup.py start        # Go live!

  COMMANDS:
    install     Install dependencies
    configure   Interactive wallet setup
    check       Verify connectivity & balances
    start       Start trade engine server
    demo        Demo mode ($10K virtual, no real funds)
    testnet     Mumbai testnet mode

  WEB UI:
    Open http://localhost:8090 after starting the server.

  For full documentation, see README.md
    """)

if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "guide"
    cmds = {
        "install": cmd_install, "configure": cmd_configure,
        "check": cmd_check, "start": cmd_start, "run": cmd_start,
        "demo": cmd_demo, "testnet": cmd_testnet, "guide": cmd_guide,
    }
    if cmd in cmds:
        cmds[cmd]()
    else:
        print(f"Unknown command: {cmd}")
        print("Available: install, configure, check, start, demo, testnet, guide")
